name: DataTug

on:
  push:
    branches: ['*']
    tags: ['*']
  workflow_dispatch:

jobs:
  ingitdb_validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: datatug/datatug-action@main
